### ISSUE TITLE
getPCA and selecting a subset of samples

### ISSUE THREAD

**Issue by SPPearce** [MatthiasLienhard/qsea#4]
The getPCA function currently filters the data based on all the samples in the qseaSet, not the ones that you have subselected in the function call:
i.e. 
`        keep=which(rowSums(getCounts(qs)) >= minRowSum )`
instead of 
`        keep=which(rowSums(getCounts(qs, samples=samples)) >= minRowSum )`

Which means that adding more samples to the qseaSet will potentially change the PCA, even if they aren't actually being used in that PCA.

(separately,  I get an error when I try and email lienhard at molgen.mpg.de)

**Comment by MatthiasLienhard** [comment]
Solved by PR#10, thank you Simon
