### ISSUE TITLE
makeTable fails when only one window is selected 

### ISSUE THREAD

**Issue by SPPearce** [MatthiasLienhard/qsea#7]
Running `makeTable` with only a single window fails when you ask for either groupMeans or samples:

```
qseaSet <- getExampleQseaSet() 
makeTable(qseaSet, norm_methods = "nrpm", keep = c(1), groupMeans = getSampleGroups(qseaSet))

Error in dimnames(x) <- dn : 
  length of 'dimnames' [2] not equal to array extent
```

This is because the `cbind` call is currently taking a transposing the M separate 1xN matrices to make a NxM matrix, rather than a 1xM*N matrix. 

I have submitted a PR to fix this, by transposing explicitly in the case where there is only one window.

**Comment by MatthiasLienhard** [comment]
Solved with PR #8
